  
---
- name: Yum Update
  gather_facts: yes
  hosts: default

  tasks:
        - name: Perform yum update of all packages
          yum:
            name: '*'
            state: latest
        - name: Reboot server
          command: /sbin/shutdown -r +1
          ignore_errors: true
